### PR TITLE
Removed despatched status

### PR DESCRIPTION
**Pull request by mcribbinscurri**

### CODE REVIEW

**Comment by mcribbinscurri** [comment]
@dnedbaylo J's decision. Originally came from a support query here:https://scurri.tpondemand.com/entity/8661-api-documents

**Comment by matelakat** [comment]
What's the verdict here?

**Comment by mcribbinscurri** [comment]
@matelakat Card is blocked for the moment: https://scurri.tpondemand.com/entity/8661-api-documents. Deleting PR.

**Comment by dnedbaylo** [comment]
Let's kill the PR.

**Pull request closed without merging**
